### ISSUE TITLE
Scan Configuration Typo + Feedback on Scan Configurations Naming

### ISSUE THREAD

**Issue by ghost** [PortSwigger/ci-cd-platform-scanning-examples#1]
Hey,

This comment contains a typo:

https://github.com/PortSwigger/ci-cd-platform-scanning-examples/blob/84ad10b89c9643835a87b68bf8f79962d5fb551e/ci-driven-scan-config-template.yml#L45C1-L46C40

It should be

`- Crawl and Audit - CICD Optimized` instead of `- Crawl and Audit - CICD optimized`

While I'm addressing this, I might add that I'm not a big fan of the syntax here. One small typo and the pipeline will fail because it doesn't recognize the scan config. Is it possible to maybe add a list with IDs instead? For instance, give `- Crawl and Audit - CICD Optimized` an ID like #1337 so that we can mention them like so

```
scanConfigurations:
  builtIn:
  - 1337
```

or something similar to avoid this. I spent a good couple minutes just to find out it was a non-capitalized 'o' that caused the config to be incorrect.

Thanks for an otherwise great software.

**Comment by Maia-PortSwigger** [comment]
Thank you for bringing this to our attention. We have corrected the typo and forwarded your feedback to the relevant team.

313b495671105485b8db2a489abe443e7d5b922c
1d5cad340a9d14b174ab02529fbc24ac4515dbe2
