### ISSUE TITLE
Update Template to match newest update

### ISSUE THREAD

**Issue by ghost** [PortSwigger/ci-cd-platform-scanning-examples#3]
Hi everyone :) I noticed that there's a lot of new functionality in the latest release, adding more fields to the config file.

https://portswigger.net/burp/documentation/enterprise/user-guide/ci-cd/ci-driven-scans/create-config

Please update the config file to contain this as well as this will save a lot of time knowing what info I can put and where in the config.

Thanks!

**Comment by Maia-PortSwigger** [comment]
Hi, thank you for your message.

The templates in this repo are now deprecated and have been removed in favour of extracting the current template directly from the container. The template in the readme is intended as an example output from the container, and won't be updated each release. That being said, I’ve raised your points with our development team to see if we can still update this repo when major features are added in the future.

**Comment by ghost** [comment]
Hi, that sounds good. However, please have a look at how your documentation on the PortSwigger website looks like. Sometimes it doesn't really align with the stuff that's on Github. Many thanks!
